addons:
  postgresql: 9.6
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - docker-ce
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - mkdir tmp/db/postgres-data -p
  - mkdir tmp/log -p
  - cp config/deploy/travis-ci/database.yml config/database.yml
  - cp config/deploy/travis-ci/config.yml config/config.yml
  - cp config/deploy/travis-ci/secrets.yml config/secrets.yml
  - cp config/deploy/travis-ci/Dockerfile ../
  - cp config/deploy/travis-ci/docker-compose.yml ../
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo docker-compose build
  - sudo docker-compose run salsa rake db:create
  - sudo docker-compose run salsa rake db:schema:load
  - sudo docker-compose run salsa rake db:migrate
  - sudo docker-compose run salsa rake db:seed

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - sudo docker-compose run salsa rake db:schema:load RAILS_ENV=test
  - sudo docker-compose run salsa rake db:migrate RAILS_ENV=test
  - bundle exec rspec
  - sudo docker-compose run salsa bash ./cucumber
dist: trusty
language: ruby
rvm:
  - 2.4.1
services:
  - redis-server
sudo: required
